name: Restore or Build Sysroot
description: Builds an armv7 sysroot for the provided distribution
inputs:
  sysroot-id:
    description: The sysroot ID to use when caching and publishing
    required: true
  sysroot-name:
    description: The sysroot name to use in the filesystem (locally) and for generating a package
  distribution:
    description: The name of the distribution to build a sysroot for
    required: true
runs:
  using: "composite"
  steps:
    - name: Restore Sysroot
      id: restore-sysroot
      uses: actions/cache/restore@v4
      with:
        key: ${{ inputs.sysroot-id }}
        path: ${{ inputs.sysroot-name }}
    - if: ${{ steps.cache-sysroot.outputs.cache-hit != 'true' }}
      name: Build
      shell: bash
      env:
        DISTRIBUTION: ${{ inputs.distribution }}
      run: ./build-sysroot.sh `echo ${DISTRIBUTION/-/:}` ${{ inputs.sysroot-name }}
    - name: Compress
      shell: bash
      run: tar -czf ${{ inputs.sysroot-name }}.tar.gz ${{ inputs.sysroot-name }}
    - uses: actions/upload-artifact@v4
      name: Publish
      with:
        name: ${{ inputs.sysroot-id }}
        path: ${{ inputs.sysroot-name }}.tar.gz
    - name: Cache Sysroot
      id: cache-sysroot
      uses: actions/cache/save@v4
      with:
        key: ${{ inputs.sysroot-id }}
        path: ${{ inputs.sysroot-name }}
